### ISSUE TITLE
make the made-with page more dynamic and inviting and inspiring

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma.org#23]
it would be good to have a table view we could rank by year or name

it would be good to have a featured project at the top we can easily change to make it more exciting and less drab (or maybe that is needed at the entry page of the site)

not as dynamic and sales pitchy as https://www.ableton.com/ but less corporate maybe. strange balance to strike.

**Comment by jamesb93** [comment]
I agree it is just enumerative at the moment. I live in constant fear of mobile/desktop parity but I will endeavour to be more adventurous on this front - it is after all definitely technically possible to do something that looks great and works on both. I'm really open to any kind of design ideas that are out there, I'm not a good designer at all. What I really like about the Ableton one is the way that they use asymmetry in parts where its more evocative but then the gridded layout for other articles.

I am averse to sorting or categorising by year, it immediately evokes boredom in me and to be honest, I don't think people will really care how these nuggets of information fit on a timeline. I sort of just want to be thrown things, so the idea of a featured article is really good. We could even just randomise it each week/day/month :).

I think that this kind of niche is definitely something we could be using a designer for either to fully offload or to provide me with wireframes to work from.

**Comment by jamesb93** [comment]
To add more to this, perhaps something with a masonry layout would be good?

https://masonry.desandro.com/

**Comment by jamesb93** [comment]
Okay, I totally thought this was about the made with flucoma learn website page 😄  but the sentiment still stands.
